### ISSUE TITLE
Sometimes players from a different server do not appear. Likely due to logic error in how join packets are sent.

### ISSUE THREAD

**Issue by Jaxkr** [Jaxkr/mammoth#31]

**Comment by luludotdev** [comment]
Commit 22c895f10ef28df51c2d1d42cb9b4158ba571b47 introduced the new bug. Previously existing players would only show to a newly joined client once a `LocalMessage` was received for their UUID.

**Comment by Jaxkr** [comment]
Caused because ensurePlayerHasJoinPackets was refactored into ProtocolManager.sendJoinPacket which only gets called when the entity is first created. This means that if a player logs off and logs back on, they won't be able to see anyone unless that person relogs.
