### ISSUE TITLE
Sometimes players don't load their data for several seconds and snap back to an old position.

### ISSUE THREAD

**Issue by Jaxkr** [Jaxkr/mammoth#51]

**Comment by luludotdev** [comment]
I have a theory that this is just the WorldQL server processing all incoming RecordRead requests before getting to the player profile. Would need to profile to confirm.

If so, could be solved by ensuring the profile read happens before chunk loads. Not entirely sure how to go about doing this.

**Comment by Jaxkr** [comment]
I've solved this by moving player storage back to redis. WorldQL is designed for spatial messages and data and it works great for player movement and blocks.
Player inventory information doesn't need to be indexed by location and we want a simple k-v solution.
